# Generated by Django 6.1 on 2026-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
