# Generated by Django 6.1 on 2026-09-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='drawdown_warning_threshold',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
