# Generated by Django 6.1 on 2026-08-18 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('broker', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('position_size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.CharField(blank=True, max_length=100)),
                ('setup', models.CharField(blank=True, max_length=100)),
                ('session', models.CharField(blank=True, max_length=50)),
                ('entry_reason', models.TextField(blank=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('emotions', models.TextField(blank=True)),
                ('mistakes', models.TextField(blank=True)),
                ('lessons', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('TRADINGVIEW', 'TradingView'), ('BROKER', 'Broker'), ('IMPORT', 'Import')], default='MANUAL', max_length=20)),
                ('external_trade_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.tradingaccount')),
            ],
        ),
    ]
