# Generated by Django 6.1 on 2026-08-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingaccount',
            old_name='account_number',
            new_name='account_identifier',
        ),
    ]
