# Generated by Django 6.1 on 2026-08-19 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_rename_account_number_tradingaccount_account_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='emotions',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='entry_reason',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_reason',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='mistakes',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='session',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='strategy',
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_trade_analysis', models.TextField(blank=True)),
                ('entry_reason', models.TextField(blank=True)),
                ('market_analysis', models.TextField(blank=True)),
                ('emotions', models.TextField(blank=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('mistakes', models.TextField(blank=True)),
                ('lessons', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='trading.trade')),
            ],
        ),
    ]
