# Generated by Django 6.1 on 2026-08-27 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_strategy_trade_strategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('PROFIT', 'Profit Target'), ('TRADE_COUNT', 'Trade Count'), ('WIN_RATE', 'Win Rate'), ('JOURNAL_COMPLETION', 'Journal Completion'), ('MAX_LOSS', 'Maximum Loss'), ('AVERAGE_RISK', 'Average Risk')], max_length=30)),
                ('target', models.DecimalField(decimal_places=2, max_digits=15)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='trading.tradingaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
