# Generated by Django 6.1 on 2026-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
