# Generated by Django 6.1 on 2026-09-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_tradingaccount_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
