# Generated by Django 6.1 on 2026-09-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_tradingaccount_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='webhook_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
