# Generated by Django 6.1 on 2026-09-02 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_tradingaccount_webhook_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(condition=models.Q(('external_trade_id', ''), _negated=True), fields=('account', 'source', 'external_trade_id'), name='unique_external_trade_per_account_source'),
        ),
    ]
