# Generated by Django 6.1 on 2026-09-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_trade_unique_external_trade_per_account_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingaccount',
            old_name='account_identifier',
            new_name='account_number',
        ),
    ]
