# Generated by Django 6.1 on 2026-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_rename_account_identifier_tradingaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='market_type',
            field=models.CharField(choices=[('FOREX', 'Forex'), ('CRYPTO', 'Crypto'), ('STOCK', 'Stock'), ('FUTURES', 'Futures'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='position_size_unit',
            field=models.CharField(choices=[('UNIT', 'Units'), ('STANDARD_LOT', 'Standard Lots'), ('MINI_LOT', 'Mini Lots'), ('MICRO_LOT', 'Micro Lots'), ('SHARE', 'Shares'), ('CONTRACT', 'Contracts')], default='UNIT', max_length=20),
        ),
    ]
