# Generated by Django 6.1 on 2026-09-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_trade_market_type_trade_position_size_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='risk_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
