# Generated by Django 6.1 on 2026-09-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_trade_risk_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='period',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
    ]
